# Generated by Django 6.0.1 on 2026-01-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phoneNo', models.CharField(max_length=20)),
                ('shippingAddress', models.TextField()),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
